---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
  delegate_to: localhost

- name: Clone git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ temp_dir.path }}"
    version: "{{ git_version }}"
    force: true
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
  when:
    - git_repo is defined
    - git_version is defined
  delegate_to: localhost

- name: Use config file from git as variable
  ansible.builtin.slurp:
    src: "{{ temp_dir.path }}/.config.yml"
  register: __temp_var
  delegate_to: localhost
  when:
    - git_repo is defined
    - git_version is defined

- name: Load config file from git
  ansible.builtin.set_fact:
    __config: "{{ __temp_var.content | b64decode | from_yaml }}"
  when:
    - git_repo is defined
    - git_version is defined

- name: Deploy files
  ansible.builtin.copy:
    src: "{{ temp_dir.path }}/{{ item.file }}"
    dest: "/{{ item.file }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    # remote_src: yes
  loop: "{{ __config.files }}"
  when:
    - __config is defined

- name: Remove temporary directory
  ansible.builtin.file:
    name: "{{ temp_dir.path }}"
    state: absent
  tags: molecule-idempotence-notest
  delegate_to: localhost
