---

- name: Debug run tree command
  ansible.builtin.command: tree /config
  register: tree_output

- name: Show tree command output
  ansible.builtin.debug:
    var: tree_output.stdout_lines

- name: Download configs for a server
  ansible.builtin.include_tasks: server.yml
