---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Clone git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ temp_dir.path }}"
    version: "{{ git_version }}"
    force: true

- name: Use config file from git as variable
  ansible.builtin.slurp:
    src: "{{ temp_dir.path }}/{{ ansible_hostname }}.yaml"
  register: __temp_var

- name: Set variable from config file
  ansible.builtin.set_fact:
    __server: "{{ __temp_var.content | b64decode | from_yaml }}"

- name: Debug config
  ansible.builtin.debug:
    var: __server

- name: Start configuration tasks
  ansible.builtin.include_tasks: config.yml
  vars:
    __loop_config: "{{ item }}"
  loop: "{{ __server }}"
  loop_control:
    loop_var: __loop_server
