---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: __server_temp
  changed_when: false

- name: Clone git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ __server_temp.path }}"
    version: "{{ git_version }}"
    force: true
  changed_when: false

- name: Use config file from git as variable
  ansible.builtin.slurp:
    src: >-
      {{ __server_temp.path }}/{{ ansible_hostname }}.yaml
  register: __server_slurp

- name: Set variable from config file
  ansible.builtin.set_fact:
    __server: >-
      {{ __server_slurp.content | b64decode | from_yaml }}

- name: Debug config
  ansible.builtin.debug:
    var: __server

- name: Start configuration tasks
  ansible.builtin.include_tasks: config.yml
  loop: "{{ __server }}"
  loop_control:
    loop_var: __loop_server

- name: Remove temporary directory
  ansible.builtin.file:
    name: "{{ __server_temp.path }}"
    state: absent
  changed_when: false
