---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server01
    image: rockylinux:9
    pre_build_image: false
    privileged: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        git_repo: "https://github.com/truestory1/hcv-servers"
        git_version: "master"
verifier:
  name: ansible
