---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server01
    image: rockylinux:9
    pre_build_image: false
    privileged: false
provisioner:
  name: ansible
verifier:
  name: ansible
