---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - tree

    - name: Ensure git repos are marked as safe
      ansible.builtin.shell: |-
        git config --global --add safe.directory /config/hcv-servers
        git config --global --add safe.directory /config/hcv-config-01

    # - name: Ensure git repository is sync from local host to remote container
    #   ansible.posix.synchronize:
    #     src: "/home/an/src/personal/hcv-config-01"
    #     dest: "/home/an/src/personal/hcv-config-01"
