---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - tree
        - rsync

    # - name: Ensure git repository is sync from local host to remote container
    #   ansible.posix.synchronize:
    #     src: "/home/an/src/personal/hcv-config-01"
    #     dest: "/home/an/src/personal/hcv-config-01"
