---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - tree
        - mc
