---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Create temporary directory for server config
      ansible.builtin.tempfile:
        state: directory
      register: __verify_temp

    - name: Clone servers repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ __verify_temp.path }}"
        version: "{{ git_version }}"
        force: true

    - name: Read server configuration
      ansible.builtin.slurp:
        src: "{{ __verify_temp.path }}/{{ ansible_hostname }}.yaml"
      register: __verify_server_raw

    - name: Parse server configuration
      ansible.builtin.set_fact:
        __verify_server: >-
          {{ __verify_server_raw.content | b64decode | from_yaml }}

    - name: Clean up servers temp directory
      ansible.builtin.file:
        path: "{{ __verify_temp.path }}"
        state: absent

    - name: Verify deployed configurations
      ansible.builtin.include_tasks: verify_config.yml
      loop: "{{ __verify_server }}"
      loop_control:
        loop_var: __verify_config_item
